### ISSUE TITLE
Improve JSON decoding strategy

### ISSUE THREAD

**Issue by DaniruKun** [mgallo/openai.ex#13]
### Describe the feature or improvement you're requesting

In the current implementation, the HTTP client is very unsafe and slow: https://github.com/mgallo/openai.ex/blob/main/lib/openai/client.ex#L15

Calling `String.to_atom/1` is considered a bad practice and should be avoided in frequent code paths like this, since this creates new atoms in the VM memory, which will never be GCed.

The responses are also unstructured for mostly the same reason.
Not to mention that `JSON` as a library is horribly slow compared to all the other engines: https://gist.github.com/devinus/f56cff9e5a0aa9de9215cf33212085f6

My suggestions:

- Replace `JSON` with `Jason` or `Poison`
- Switch to safe atom creation strategy (pretty easy with Jason/Poison to not have to manually do string conversion to existing atoms)
- Define core API models as structs, and directly decode to them

**Comment by mgallo** [comment]
Thank you very much for your report and valuable suggestions 🙏 . I'll have a look at it as soon as I can, I was already planning to replace `JSON` with `Jason` (which, from the benchmarks, and for what I need, seems the best), and it absolutely makes sense to define the API models as struct and remove that `String.to_atom/1`.

**Comment by sergiotapia** [comment]
I recommend using `Jason` since it's the default in Phoenix and many other projects. It's the fastest implementation as well.

+1 to decoding to structs.

**Comment by mgallo** [comment]
Hey, I replaced `Json` with `Jason` in `0.4.0`.  For backward compatibility, no changes have yet been made to the transformation from string to atoms.

Now that the library supports all the new OpenAI APIs, I plan to release a future version that will introduce `structs` and probably the ability to choose how to parse the response object (need to think about that). I will also add a compatibility layer for applications that currently use the library, so as not to break too much existing implementations.

Release log: https://github.com/mgallo/openai.ex/releases/tag/v0.4.0
Hex.pm: https://hexdocs.pm/openai/0.4.0/api-reference.html

**Comment by DaniruKun** [comment]
Thanks!
