### ISSUE TITLE
Audio Transcription API support

### ISSUE THREAD

**Issue by Miserlou** [mgallo/openai.ex#19]
### Describe the feature or improvement you're requesting

There are OpenAI API endpoints for audio transcription and translation, would be great if this lib supported them.

### Additional context

https://platform.openai.com/docs/api-reference/audio

**Comment by Miserlou** [comment]
Competing implementation: https://github.com/hernanat/open_ai_ex/pull/5/files

**Comment by Miserlou** [comment]
hell yeah

**Comment by mgallo** [comment]
Hey, released in v0.4.0:

Release log: https://github.com/mgallo/openai.ex/releases/tag/v0.4.0
Hex.pm: https://hexdocs.pm/openai/0.4.0/api-reference.html

audio docs: https://github.com/mgallo/openai.ex#audio_transcriptionfile_path-params
