### ISSUE TITLE
Make URL target a config option to allow for easier local testing and mocking

### ISSUE THREAD

**Issue by rwdaigle** [mgallo/openai.ex#20]
### Describe the feature or improvement you're requesting

I would like to be able use [Bypass](https://github.com/PSPDFKit-labs/bypass), or similar, to write local integrations tests without having to hit the actual OpenAI API. Key to this is the ability to set openai.ex's URL, currently hardcoded as `@openai_url` within `OpenAI.Config`.

I would like to propose that the `openai_url` be overridable by a new `api_url` config option:

```elixir
config :openai,
  api_key: "your-api-key",
  organization_key: "your-organization-key",
  api_url: "http://localhost/",
  http_options: [recv_timeout: 2_000] 
```

This could then be overridden in a test setup block like so:

```elixir
  setup %{conn: conn} do

    # Setup mock OpenAI server
    bypass = Bypass.open()
    Application.put_env(:openai, :api_url, "http://localhost:#{bypass.port}/")

    # ...

    {:ok, bypass: bypass, conn: conn}
  end
```

Thoughts?

**Comment by mgallo** [comment]
Hey, thanks for the suggestion and for the contribution! I merged your PR, and it is released in 0.4.0 

Release log: https://github.com/mgallo/openai.ex/releases/tag/v0.4.0
Hex.pm: https://hexdocs.pm/openai/0.4.0/api-reference.html

**Comment by rwdaigle** [comment]
🙏

**Comment by Madd0g** [comment]
can you please give me a pointer on how to use it?

I tried creating in my config.exs

```
config :openai,
  api_key: "your-api-key",
  organization_key: "your-organization-key",
  api_url: "http://localhost:8000"
```

and on startup, I get this message:

```
You have configured application :openai in your configuration file,
but the application is not available.

This usually means one of:

  1. You have not added the application as a dependency in a mix.exs file.

  2. You are configuring an application that does not really exist.

Please ensure :openai exists or remove the configuration.
```

I tried changing `:openai` to `:openai_ex` and that error disappears, but I still get an error about the api_key from openai, so looks like the config isn't loaded?

I don't see any parameters in `OpenaiEx.new` or `ChatCompletion.create` to make it read the config or to pass another config.

I'm new to elixir, so I might have missed something.
