### ISSUE TITLE
API key error on prod: You didn't provide an API key. You need to provide your API key in an Authorization header

### ISSUE THREAD

**Issue by sergiotapia** [mgallo/openai.ex#50]
I'm having this problem on prod. The OpenAI call errors out with:

> ** (MatchError) no match of right hand side value: {:error, %{"error" => %{"code" => nil, "message" => "You didn't provide an API key. You need to provide your API key in an Authorization header using Bearer auth (i.e. Authorization: Bearer YOUR_KEY), or as the password field (with blank username) if you're accessing the API from your browser and are prompted for a username and password. You can obtain an API key from https://platform.openai.com/account/api-keys.", "param" => nil, "type" => "invalid_request_error"}}}

Example I run on iex, this works in dev, does not in prod:

```
OpenAI.chat_completion(
  model: "gpt-3.5-turbo",
  messages: [%{role: "user", content: "Hello how are you?"}]
)
```

I verified that the ENV keys are set properly on prod as well using `echo $OPENAI_API_KEY`.

My `config.exs` looks like this:

```
config :openai,
  # find it at https://platform.openai.com/account/api-keys
  api_key: System.get_env("OPENAI_API_KEY"),
  # find it at https://platform.openai.com/account/org-settings under "Organization ID"
  organization_key: System.get_env("OPENAI_ORGANIZATION_ID")
```

Any suggestions?

**Comment by sergiotapia** [comment]
Adding the same config to `runtime.exs` fixed the issue. Should I keep both in `config.exs` and `runtime.exs`?

**Comment by bfolkens** [comment]
@sergiotapia `config.exs` is compile-time (`get_env/1` is executed during the build) and `runtime.exs` is run-time (`get_env/1` is executed when the program runs).  I would just put any `get_env/1` calls in `runtime.exs` and remove them in `config.exs` to avoid confusion.

Ref: https://elixir-lang.org/getting-started/mix-otp/config-and-releases.html#configuration

**Comment by mgallo** [comment]
thanks @bfolkens for the answer, and sorry @sergiotapia for the delay, I'm really busy these days.. I'll add a better explanation in the **Configuration** section of the docs, to avoid confusion. Thanks!
