### ISSUE TITLE
Hex package has hardcoded api key

### ISSUE THREAD

**Issue by rakshans1** [mgallo/openai.ex#7]
<img width="769" alt="image" src="https://user-images.githubusercontent.com/12949352/208611631-ff777511-3a7f-4c59-9481-1d2f3a00f297.png">

**Comment by mgallo** [comment]
thanks foir signaling it, I need to implement a proper pipeline to avoid this kind of issues in the future. It is fixed in [v0.2.1](https://github.com/mgallo/openai.ex/releases/tag/v0.2.1).
